---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- path: content/projects
  label: Projects
  create: all
  default_front_matter_template: projects
- path: content/web
  label: Web
  create: all
- path: content/blog
  label: Blog
  create: all
  default_front_matter_template: blog
upload_dir: static/img
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
version: 0.38.1
