---
upload_path: "/static/img"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
  projects:
    default_front_matter_template: projects
  blog:
    default_front_matter_template: blog
version: 0.31.1
